# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Labádi Gergely
tagline:          '&lt;/filológia&gt;'
description:      'digitális és nem digitális bölcsészet • 18–19. századi magyar irodalom • olvasástörténet • szövegek'
url:              http://labadigergely/github.io
baseurl:          '/'
paginate:         5

author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

# Custom vars
#version:          1.0.0

github:
 # repo:           https://github.com/poole/lanyon
